- customVariables: []
  description: JNDI properties file
  labels:
  - capability=java-ee6+
  - capability=java-ee
  - discovery
  links: []
  message: "\n                          \n                          The JNDI automatically
    reads the application resource files from all components in the applications'
    classpaths.\n                          The JNDI then makes the properties from
    these files available to the service providers.\n\n                          Please
    ensure the property values listed in this file are available to JBoss EAP.\n                          \n
    \                       "
  ruleID: environment-dependent-calls-03500
  tag:
  - JNDI properties file
  when:
    as: default
    builtin.file:
      pattern: jndi\.properties
